name: Update README with Random Cat Image

on:
  # Schedule: Consider adjusting the frequency
  schedule:
    - cron: '*/1 * * * *'  # Runs every hour (optional)

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout repository code

      - uses: actions/setup-node@v3
        with:
          node-version: 20  # Set Node.js version to 20

      - name: Install Dependencies (if applicable)
        run: npm install  # Install dependencies from package.json (optional)

      - name: Download Random Cat Image using Node.js
        run: |
          node download-cat-image.js  # Replace with your script name
          echo "Downloaded cat image: $CAT_IMAGE_URL"  # For logging purposes (optional)

      - name: Update README with Image Link
        uses: josantonius/github-action-markdown-formatter@v2  # Update README content
        with:
          content: |
            # Update this section with your desired location in the README
            ## Random Cat of the Day

            ![Random Cat]($CAT_IMAGE_URL)

      - name: Commit and Push Changes (using a personal access token)
        uses: ad-action/github-push@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Update branch as needed
          message: "Update README with Random Cat Image"

# Define your Node.js script (save as download-cat-image.js)
