name: Update README with Random Cat Image

on:
  # Schedule: Consider adjusting the frequency
  schedule:
    - cron: '*/1 * * * *'  # Runs every hour (optional)

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout repository code

      - name: Fetch Random Cat Image URL
        run: |
          cat_url=$(curl https://cataas.com/cat/says/hello | jq -r '.url')
          echo "Random Cat Image URL: $cat_url"  # For logging purposes (optional)

      - name: Download Cat Image
        uses: actions/download-artifact@v3  # Download image
        with:
          name: cat-image  # Update name as needed (optional)
          path: .

      - name: Download Image Using cURL (alternative)
        run: |
          curl -o cat-image.jpg $CAT_URL  # Download using cURL (requires CAT_URL variable)

      - name: Update README with Image Link
        uses: josantonius/github-action-markdown-formatter@v2  # Update README content
        with:
          content: |
            # Update this section with your desired location in the README
            ## Random Cat of the Day

            ![Random Cat]($CAT_URL)

      - name: Commit and Push Changes (using a personal access token)
        uses: ad-action/github-push@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Update branch as needed
          message: "Update README with Random Cat Image"
